### ISSUE TITLE
Problems 

### ISSUE THREAD

**Issue by nicolasandrada** [Hrober0/Cable-physics#1]
Hi, I wanted to use your script but I get these 3 errors. 

* **Scripts\Connector.cs(5,7): error CS0246: The type or namespace name 'Logic' could not be found (are you missing a using directive or an assembly reference?)**
* **Scripts\Connector.cs(6,7): error CS0246: The type or namespace name 'Audio' could not be found (are you missing a using directive or an assembly reference?)**
* **Scripts\PhysicCableCon.cs(10,29): error CS0506: 'PhysicCableCon.Awake()': cannot override inherited member 'Liftable.Awake()' because it is not marked virtual, abstract, or override**

sorry for the inconvenience

**Comment by Hrober0** [comment]
Hi,
The scripts have several dependencies because they are part of a larger game.

The scripts reference to
- the logic of the game,
- custom attributes: https://github.com/dbrizov/NaughtyAttributes
- outlines: https://assetstore.unity.com/packages/tools/particles-effects/quick-outline-115488

The code has been published for reference, 
but you can easily remove those dependencies and make it work without them.

**Comment by nicolasandrada** [comment]
Thank you so much :D
